name: ticket_app
description: A Flutter application for event ticket management
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  pdf: ^3.10.11
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  intl: ^0.18.1
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6